import { z } from 'zod';
import { hexColorSchema } from '../../shared/color';

/** Thèmes disponibles pour le tileset vu de côté (mode plateformer). */
export const SIDE_TILESET_THEMES = ['grassland', 'cave', 'castle', 'snow', 'desert'] as const;
export type SideTilesetTheme = (typeof SIDE_TILESET_THEMES)[number];

export const SIDE_PALETTE_KEYS = [
  'surface',
  'surfaceDark',
  'surfaceLight',
  'fill',
  'fillDark',
  'fillLight',
  'brick',
  'brickDark',
  'stone',
  'stoneDark',
  'wood',
  'woodDark',
  'water',
  'waterLight',
  'leaf',
  'leafDark',
  'accent',
  'outline',
] as const;

export type SidePaletteKey = (typeof SIDE_PALETTE_KEYS)[number];
export type SideTilesetPalette = Record<SidePaletteKey, string>;

const SIDE_PALETTE_DOC: Record<SidePaletteKey, string> = {
  surface: 'Bande du haut, lisible en tant que surface (herbe, neige, sable, dallage clair)',
  surfaceDark: 'Ombre / veines de la surface',
  surfaceLight: 'Reflet de la surface',
  fill: 'Intérieur du bloc (terre, roche) — doit se raccorder sur les 4 bords',
  fillDark: 'Ombre / mouchetures de l’intérieur',
  fillLight: 'Reflet de l’intérieur',
  brick: 'Brique',
  brickDark: 'Mortier / ombre de la brique',
  stone: 'Pierre taillée',
  stoneDark: 'Ombre de la pierre',
  wood: 'Bois (caisse, plateforme, pont, panneau, barrière)',
  woodDark: 'Ombre / grain du bois',
  water: 'Eau (semi-transparente)',
  waterLight: 'Crêtes / reflets de l’eau',
  leaf: 'Feuillage (buisson, fleurs)',
  leafDark: 'Ombre du feuillage',
  accent: 'Accent saturé (pétales, pointes des pics, bannière) — utilisé avec parcimonie',
  outline: 'Contour très sombre (jamais noir pur), utilisé sur le décor et les pics',
};

export const sideTilesetPaletteSchema = z.object(
  Object.fromEntries(SIDE_PALETTE_KEYS.map((k) => [k, hexColorSchema.describe(SIDE_PALETTE_DOC[k])])) as Record<
    SidePaletteKey,
    z.ZodString
  >,
);

/** Palettes de référence de chaque thème (utilisées hors-ligne et comme exemples pour Claude). */
export const SIDE_THEME_PALETTES: Record<SideTilesetTheme, SideTilesetPalette> = {
  grassland: {
    surface: '#5eab48',
    surfaceDark: '#3f8540',
    surfaceLight: '#94d25e',
    fill: '#8a6a46',
    fillDark: '#5e4630',
    fillLight: '#a8845c',
    brick: '#b4664a',
    brickDark: '#7c4230',
    stone: '#a3a0ad',
    stoneDark: '#666374',
    wood: '#a8703f',
    woodDark: '#6a4226',
    water: '#3c8fd4',
    waterLight: '#9ad8f4',
    leaf: '#4f9e40',
    leafDark: '#2d6a36',
    accent: '#f0c83c',
    outline: '#22182a',
  },
  cave: {
    surface: '#5a6c4c',
    surfaceDark: '#3a4632',
    surfaceLight: '#7c8c62',
    fill: '#6c5c50',
    fillDark: '#463c34',
    fillLight: '#8c7a68',
    brick: '#5c5264',
    brickDark: '#3a3442',
    stone: '#7c7284',
    stoneDark: '#4e465a',
    wood: '#7c5636',
    woodDark: '#4a3222',
    water: '#2a6c8e',
    waterLight: '#5cb4d4',
    leaf: '#8c5cb4',
    leafDark: '#5a3a82',
    accent: '#5ae4d2',
    outline: '#130f18',
  },
  castle: {
    surface: '#c8c2b6',
    surfaceDark: '#928c7e',
    surfaceLight: '#e8e2d4',
    fill: '#8c8a9c',
    fillDark: '#57556a',
    fillLight: '#aeacbc',
    brick: '#a4523e',
    brickDark: '#6e3226',
    stone: '#8c8a9c',
    stoneDark: '#57556a',
    wood: '#7c5432',
    woodDark: '#4a3020',
    water: '#3c6fc4',
    waterLight: '#9ac0f4',
    leaf: '#4c7e3c',
    leafDark: '#2e5428',
    accent: '#e8c04c',
    outline: '#181420',
  },
  snow: {
    surface: '#eaf2fa',
    surfaceDark: '#b6c6de',
    surfaceLight: '#ffffff',
    fill: '#7c8aa2',
    fillDark: '#525e72',
    fillLight: '#9ca8bc',
    brick: '#7c92b4',
    brickDark: '#4e5e7c',
    stone: '#9ca6b8',
    stoneDark: '#646e86',
    wood: '#8c5c3c',
    woodDark: '#5a3a28',
    water: '#5896c6',
    waterLight: '#c4eaf8',
    leaf: '#2c6c5c',
    leafDark: '#1a4442',
    accent: '#d84c52',
    outline: '#191d2e',
  },
  desert: {
    surface: '#e8cc8e',
    surfaceDark: '#c9a266',
    surfaceLight: '#f7e3ae',
    fill: '#c99c6c',
    fillDark: '#9c724a',
    fillLight: '#dcb684',
    brick: '#b4784a',
    brickDark: '#7c4e2c',
    stone: '#c8a274',
    stoneDark: '#8e6a4a',
    wood: '#9c6a3c',
    woodDark: '#6a4426',
    water: '#36a2ba',
    waterLight: '#9ce4e2',
    leaf: '#6c9e3c',
    leafDark: '#3e6a2c',
    accent: '#d8724c',
    outline: '#2a1a16',
  },
};
