import type { ProjectTemplate } from '@forge/core';
import type { RpgDatabaseInput, RpgSystemInput } from '../schema';
import { backgroundAsset, battlerAsset, charsetAsset, musicAsset, sfxAsset, tilesetAsset } from './assets';
import { buildInnMap, buildVillageMap } from './demoMaps';

export const DEMO_SYSTEM: RpgSystemInput = {
  title: 'Le Village de Brume',
  startMap: 'village',
  startX: 15,
  startY: 20,
  startDirection: 'up',
  party: ['lea', 'noah'],
  startGold: 50,
  zoom: 3,
  titleMusic: 'musique titre',
  mapMusic: 'musique village',
  battleMusic: 'musique combat',
  victoryMusic: 'musique victoire',
  sfx: {
    cursor: 'son curseur',
    confirm: 'son valider',
    cancel: 'son annuler',
    hit: 'son coup',
    heal: 'son soin',
    coin: 'son piece',
    door: 'son porte',
  },
  battleback: 'fond combat',
};

export const DEMO_DATABASE: RpgDatabaseInput = {
  actors: [
    {
      id: 'lea',
      name: 'Léa',
      charset: 'chara lea',
      level: 1,
      maxHp: 60,
      maxMp: 12,
      atk: 14,
      def: 9,
      mag: 4,
      agi: 9,
      skills: ['tranche'],
    },
    {
      id: 'noah',
      name: 'Noah',
      charset: 'chara noah',
      level: 1,
      maxHp: 42,
      maxMp: 30,
      atk: 8,
      def: 6,
      mag: 12,
      agi: 8,
      skills: ['feu', 'givre', 'soin'],
    },
  ],
  items: [
    {
      id: 'potion',
      name: 'Potion',
      description: 'Rend 50 PV à un allié.',
      price: 20,
      consumable: true,
      effect: { type: 'heal', value: 50 },
    },
    {
      id: 'ether',
      name: 'Éther',
      description: 'Rend 20 PM à un allié.',
      price: 60,
      consumable: true,
      effect: { type: 'mp', value: 20 },
    },
    {
      id: 'plume_phenix',
      name: 'Plume de phénix',
      description: 'Ramène un allié K.O. à la vie avec 40 PV.',
      price: 150,
      consumable: true,
      effect: { type: 'revive', value: 40 },
    },
    {
      id: 'cle_coffre',
      name: 'Clé du coffre',
      description: "Une vieille clé en laiton, donnée par l'Ancien.",
      price: 0,
      consumable: false,
      key: true,
      effect: { type: 'none', value: 0 },
    },
  ],
  skills: [
    {
      id: 'tranche',
      name: 'Tranche',
      description: "Un puissant coup d'épée sur un ennemi.",
      mpCost: 3,
      power: 24,
      type: 'damage',
      target: 'enemy',
      sfx: 'son coup',
    },
    {
      id: 'feu',
      name: 'Feu',
      description: 'Une boule de feu sur un ennemi.',
      mpCost: 4,
      power: 18,
      type: 'damage',
      target: 'enemy',
      sfx: 'son feu',
    },
    {
      id: 'givre',
      name: 'Givre',
      description: 'Un vent glacé frappe tous les ennemis.',
      mpCost: 7,
      power: 10,
      type: 'damage',
      target: 'allEnemies',
      sfx: 'son magie',
    },
    {
      id: 'soin',
      name: 'Soin',
      description: 'Rend des PV à un allié.',
      mpCost: 5,
      power: 20,
      type: 'heal',
      target: 'ally',
      sfx: 'son soin',
    },
    {
      id: 'eclaboussure',
      name: 'Éclaboussure',
      description: "Une vague de gelée frappe toute l'équipe.",
      mpCost: 6,
      power: 6,
      type: 'damage',
      target: 'allEnemies',
      sfx: 'son coup',
    },
  ],
  enemies: [
    {
      id: 'slime',
      name: 'Slime',
      battler: 'battler slime',
      maxHp: 20,
      maxMp: 0,
      atk: 9,
      def: 4,
      mag: 2,
      agi: 5,
      exp: 6,
      gold: 5,
      drops: [{ item: 'potion', chance: 0.2 }],
      skills: [],
    },
    {
      id: 'chauve_souris',
      name: 'Chauve-souris',
      battler: 'battler chauve-souris',
      maxHp: 16,
      maxMp: 0,
      atk: 11,
      def: 3,
      mag: 2,
      agi: 12,
      exp: 8,
      gold: 7,
      drops: [{ item: 'ether', chance: 0.1 }],
      skills: [],
    },
    {
      id: 'roi_slime',
      name: 'Roi Slime',
      battler: 'battler roi slime',
      maxHp: 140,
      maxMp: 24,
      atk: 13,
      def: 8,
      mag: 8,
      agi: 6,
      exp: 60,
      gold: 80,
      drops: [{ item: 'plume_phenix', chance: 1 }],
      skills: ['eclaboussure'],
    },
  ],
  troops: [
    { id: 'slimes', name: 'Deux slimes', members: ['slime', 'slime'] },
    { id: 'chauve_souris', name: 'Chauve-souris', members: ['chauve_souris'] },
    { id: 'mixte', name: 'Slime et chauve-souris', members: ['slime', 'chauve_souris'] },
    { id: 'roi_slime', name: 'Le Roi Slime', members: ['roi_slime'] },
  ],
};

const CHARSETS = [
  charsetAsset(
    'chara lea',
    'Léa (épéiste)',
    {
      skinTone: '#f2c9a0',
      hairColor: '#b5562b',
      hairStyle: 'ponytail',
      outfitColor: '#3b6fd6',
      outfitStyle: 'armor',
      accessory: 'none',
      prompt: 'Léa, jeune épéiste courageuse, queue de cheval rousse, armure bleue',
    },
    2001,
  ),
  charsetAsset(
    'chara noah',
    'Noah (mage)',
    {
      skinTone: '#e0b48c',
      hairColor: '#2d2a4a',
      hairStyle: 'short',
      outfitColor: '#7b3fb5',
      outfitStyle: 'robe',
      accessory: 'hat',
      prompt: 'Noah, apprenti mage en robe violette et chapeau pointu',
    },
    2002,
  ),
  charsetAsset(
    'chara mila',
    'Mila (villageoise)',
    {
      skinTone: '#f5d3b3',
      hairColor: '#e8c15a',
      hairStyle: 'long',
      outfitColor: '#d9577a',
      outfitStyle: 'dress',
      accessory: 'none',
      prompt: 'Mila, villageoise joyeuse aux longs cheveux blonds, robe rose',
    },
    2003,
  ),
  charsetAsset(
    'chara ancien',
    'Ancien Aldo',
    {
      skinTone: '#e6c09a',
      hairColor: '#dcdcdc',
      hairStyle: 'bald',
      outfitColor: '#6b5b3e',
      outfitStyle: 'robe',
      accessory: 'glasses',
      prompt: 'Vieux sage du village, crâne dégarni, lunettes, robe brune',
    },
    2004,
  ),
  charsetAsset(
    'chara aubergiste',
    'Rosa (aubergiste)',
    {
      skinTone: '#c98e62',
      hairColor: '#5a3620',
      hairStyle: 'ponytail',
      outfitColor: '#4f8a4b',
      outfitStyle: 'tunic',
      accessory: 'none',
      prompt: 'Rosa, aubergiste souriante, tablier vert',
    },
    2005,
  ),
  charsetAsset(
    'chara roi slime',
    'Roi Slime (carte)',
    {
      skinTone: '#58c46a',
      hairColor: '#3a9c4c',
      hairStyle: 'bald',
      outfitColor: '#2f7d3f',
      outfitStyle: 'robe',
      accessory: 'crown',
      prompt: 'Roi Slime : créature gélatineuse verte portant une couronne dorée',
    },
    2006,
  ),
];

export const demoTemplate: ProjectTemplate = {
  id: 'rpg-demo',
  name: 'Démo : Le Village de Brume',
  description:
    'Un petit RPG complet : village avec auberge, étang et pont, hautes herbes peuplées de monstres, ' +
    "quête de l'Ancien et combat contre le Roi Slime.",
  manifest: {
    resolution: { width: 960, height: 540 },
    pixelArt: true,
    entry: 'data/system.json',
    description: 'Démo RPG : aidez le village de Brume à se débarrasser du Roi Slime.',
  },
  files: [
    { path: 'data/system.json', content: DEMO_SYSTEM },
    { path: 'data/database.json', content: DEMO_DATABASE },
    { path: 'maps/village.json', content: buildVillageMap() },
    { path: 'maps/auberge.json', content: buildInnMap() },
  ],
  assets: [
    tilesetAsset('tiles village', 'Tuiles : village', 'village', 1001, 'Village paisible : herbe, chemins, étang'),
    tilesetAsset('tiles interieur', 'Tuiles : intérieur', 'interior', 1002, "Intérieur d'auberge chaleureuse en bois"),
    ...CHARSETS,
    battlerAsset('battler slime', 'Slime', 'slime', '#57c46a', 3001, 'Petit slime vert souriant'),
    battlerAsset('battler chauve-souris', 'Chauve-souris', 'bat', '#6a4c9c', 3002, 'Chauve-souris violette'),
    battlerAsset('battler roi slime', 'Roi Slime', 'slime', '#3f7de0', 3003, 'Roi Slime géant et bleu, couronne dorée'),
    backgroundAsset('fond combat', 'Fond de combat', 'forest', 3004, "Clairière paisible près d'un étang"),
    musicAsset('musique titre', 'Thème principal', 'epic', 4001, 'Thème héroïque et entraînant'),
    musicAsset('musique village', 'Village de Brume', 'village', 4002, 'Mélodie paisible de village'),
    musicAsset('musique auberge', 'Auberge', 'calm', 4003, 'Ambiance chaleureuse et calme'),
    musicAsset('musique combat', 'Combat', 'battle', 4004, 'Combat rythmé'),
    musicAsset('musique victoire', 'Victoire', 'happy', 4005, 'Fanfare de victoire joyeuse'),
    sfxAsset('son curseur', 'Curseur', 'blip', 5001, 'Déplacement du curseur'),
    sfxAsset('son valider', 'Validation', 'select', 5002, "Validation d'un choix"),
    sfxAsset('son annuler', 'Annulation', 'cancel', 5003, 'Annulation'),
    sfxAsset('son coup', 'Coup', 'hit', 5004, 'Coup porté en combat'),
    sfxAsset('son soin', 'Soin', 'powerup', 5005, 'Soin magique'),
    sfxAsset('son piece', 'Pièces', 'coin', 5006, "Pièces d'or"),
    sfxAsset('son porte', 'Porte', 'door', 5007, "Porte qui s'ouvre"),
    sfxAsset('son feu', 'Feu', 'explosion', 5008, 'Boule de feu'),
    sfxAsset('son magie', 'Magie', 'magic', 5009, 'Sortilège de glace'),
  ],
};
