import { z } from 'zod';
import { hexColorSchema } from '../../shared/color';

export const TILESET_THEMES = ['village', 'forest', 'dungeon', 'interior', 'desert', 'snow', 'cave'] as const;
export type TilesetTheme = (typeof TILESET_THEMES)[number];

export const PALETTE_KEYS = [
  'ground',
  'groundDark',
  'groundLight',
  'path',
  'pathDark',
  'water',
  'waterLight',
  'wall',
  'wallDark',
  'roof',
  'roofDark',
  'wood',
  'woodDark',
  'leaf',
  'leafDark',
  'stone',
  'stoneDark',
  'accent',
  'outline',
] as const;

export type PaletteKey = (typeof PALETTE_KEYS)[number];
export type TilesetPalette = Record<PaletteKey, string>;

const PALETTE_DOC: Record<PaletteKey, string> = {
  ground: 'Main floor color (grass, sand, snow, stone floor, wooden floor, cave dirt...)',
  groundDark: 'Floor shadow / tufts / seams',
  groundLight: 'Floor highlights',
  path: 'Path / road / carpet runner base',
  pathDark: 'Path shadow, pebbles, seams',
  water: 'Water base',
  waterLight: 'Water highlights and foam',
  wall: 'Building / dungeon / cave wall face',
  wallDark: 'Wall shadow, mortar',
  roof: 'Roof or ceiling base',
  roofDark: 'Roof shadow and tile edges',
  wood: 'Wood (doors, furniture, fences, trunks)',
  woodDark: 'Wood shadow and grain',
  leaf: 'Foliage (trees, bushes); cave: giant mushroom cap',
  leafDark: 'Foliage shadow',
  stone: 'Rocks, stairs, stone details',
  stoneDark: 'Stone shadow',
  accent: 'Accent (flowers, fire, crystals, fabric) - saturated, used sparingly',
  outline: 'Very dark outline color for decor objects and the void tile',
};

export const tilesetPaletteSchema = z.object(
  Object.fromEntries(PALETTE_KEYS.map((k) => [k, hexColorSchema.describe(PALETTE_DOC[k])])) as Record<
    PaletteKey,
    z.ZodString
  >,
);

/** Palettes de référence de chaque thème (utilisées hors-ligne et comme exemples pour Claude). */
export const THEME_PALETTES: Record<TilesetTheme, TilesetPalette> = {
  village: {
    ground: '#5eab48',
    groundDark: '#3f8540',
    groundLight: '#94d25e',
    path: '#cfa86e',
    pathDark: '#9c784a',
    water: '#3c8fd4',
    waterLight: '#9ad8f4',
    wall: '#eadbb6',
    wallDark: '#b89c76',
    roof: '#c4503c',
    roofDark: '#8a3028',
    wood: '#a8703f',
    woodDark: '#6a4226',
    leaf: '#4f9e40',
    leafDark: '#2d6a36',
    stone: '#a3a0ad',
    stoneDark: '#666374',
    accent: '#f0c83c',
    outline: '#22182a',
  },
  forest: {
    ground: '#3f7d3c',
    groundDark: '#2a5632',
    groundLight: '#6da64c',
    path: '#8e6c4a',
    pathDark: '#5e4632',
    water: '#2f7c8c',
    waterLight: '#80c8c4',
    wall: '#8c6a48',
    wallDark: '#5a4230',
    roof: '#a88446',
    roofDark: '#6c5028',
    wood: '#7c5432',
    woodDark: '#4a3020',
    leaf: '#2f7d3c',
    leafDark: '#1a4a2c',
    stone: '#81806f',
    stoneDark: '#52524a',
    accent: '#e8649a',
    outline: '#15191a',
  },
  dungeon: {
    ground: '#5c5a6a',
    groundDark: '#3e3c4c',
    groundLight: '#7e7c8e',
    path: '#4a4656',
    pathDark: '#302c3a',
    water: '#3c6c5c',
    waterLight: '#74ae90',
    wall: '#6c6a7c',
    wallDark: '#434150',
    roof: '#2e2c38',
    roofDark: '#1c1a24',
    wood: '#6e4c32',
    woodDark: '#3e2a1c',
    leaf: '#4c6e3c',
    leafDark: '#2e4428',
    stone: '#8c8a9c',
    stoneDark: '#57556a',
    accent: '#f4a232',
    outline: '#110f17',
  },
  interior: {
    ground: '#b67e4a',
    groundDark: '#875a32',
    groundLight: '#d6a066',
    path: '#a8384a',
    pathDark: '#762232',
    water: '#4a9ad4',
    waterLight: '#a8e0f4',
    wall: '#eadfc4',
    wallDark: '#bba684',
    roof: '#6c4a38',
    roofDark: '#442e22',
    wood: '#9c6638',
    woodDark: '#5e3a20',
    leaf: '#4a9e4c',
    leafDark: '#2d6a36',
    stone: '#bdb8c2',
    stoneDark: '#817c8c',
    accent: '#dca63a',
    outline: '#24171c',
  },
  desert: {
    ground: '#e8cc8e',
    groundDark: '#c9a266',
    groundLight: '#f7e3ae',
    path: '#c99c6c',
    pathDark: '#9c724a',
    water: '#36a2ba',
    waterLight: '#9ce4e2',
    wall: '#dcac74',
    wallDark: '#a8784a',
    roof: '#c46a3c',
    roofDark: '#8a4426',
    wood: '#9c6a3c',
    woodDark: '#6a4426',
    leaf: '#6c9e3c',
    leafDark: '#3e6a2c',
    stone: '#c8a274',
    stoneDark: '#8e6a4a',
    accent: '#d84c4c',
    outline: '#2a1a16',
  },
  snow: {
    ground: '#eaf2fa',
    groundDark: '#b6c6de',
    groundLight: '#ffffff',
    path: '#aebacc',
    pathDark: '#7c8aa2',
    water: '#5896c6',
    waterLight: '#c4eaf8',
    wall: '#8c5c3c',
    wallDark: '#5a3a28',
    roof: '#dfe8f4',
    roofDark: '#98a8c4',
    wood: '#8c5c3c',
    woodDark: '#5a3a28',
    leaf: '#2c6c5c',
    leafDark: '#1a4442',
    stone: '#9ca6b8',
    stoneDark: '#646e86',
    accent: '#d84c52',
    outline: '#191d2e',
  },
  cave: {
    ground: '#6c5c50',
    groundDark: '#4a3e36',
    groundLight: '#8c7a68',
    path: '#584a42',
    pathDark: '#3c322c',
    water: '#2a6c8e',
    waterLight: '#5cb4d4',
    wall: '#5c5264',
    wallDark: '#3a3442',
    roof: '#3e3846',
    roofDark: '#2a2630',
    wood: '#7c5636',
    woodDark: '#4a3222',
    leaf: '#8c5cb4',
    leafDark: '#5a3a82',
    stone: '#7c7284',
    stoneDark: '#4e465a',
    accent: '#5ae4d2',
    outline: '#130f18',
  },
};
